

export const MapActionTypes = {
    ADD_TERM:'ADD_TERM',
    SET_SEARCH_FLAG: 'SET_SEARCH_FLAG',
    CLEAR_SEARCH_FLAG: 'CLEAR_SEARCH_FLAG',
    SET_SEARCH_VALUE1: 'SET_SEARCH_VALUE1',
    SET_SEARCH_VALUE2: 'SET_SEARCH_VALUE2',
    SET_SEARCH_VALUE3: 'SET_SEARCH_VALUE3',
    SET_LOCATION_VALUE: 'SET_LOCATION_VALUE',
    CLEAR_TERMS:'CLEAR_TERMS',
    ADD_SEARCH_RESULT:'ADD_SEARCH_RESULT',
    ADD_SEARCH_RESULT_DETAIL: 'ADD_SEARCH_RESULT_DETAIL',
    CLEAR_SEARCH_RESULTS:'CLEAR_SEARCH_RESULTS',
    ADD_LOCATION_VALUE:'ADD_LOCATION_VALUE',
    ADD_SEARCH_RESULT_ID:'ADD_SEARCH_RESULT_ID',
    CLEAR_SEARCH_RESULTS_ID_LIST:'CLEAR_SEARCH_RESULTS_ID_LIST',
};