

export const MapActionTypes = {
    ADD_TERM:'ADD_TERM',
    SET_SEARCH_VALUE1: 'SET_SEARCH_VALUE1',
    SET_SEARCH_VALUE2: 'SET_SEARCH_VALUE2',
    SET_LOCATION_VALUE: 'SET_LOCATION_VALUE',
    SET_MAP_WIDGET: 'SET_MAP_WIDGET'
};